[project]
name = "pre-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hzc", email = "huangzhch@deepinsighttech.com" }
]
requires-python = ">=3.12"
dependencies = [
    "google-search-results>=2.4.2",
    "openai>=3.0.0",
    "python-dotenv>=1.2.2",
]

[project.scripts]
pre-agent = "pre_agent:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
